"""make phone_number nullable for google signin users

Revision ID: 13d98aeb2105
Revises: 88e5dcccd12f
Create Date: 2026-05-05 15:21:00.810555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d98aeb2105'
down_revision: Union[str, None] = '88e5dcccd12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
