"""add remaining 9 tables

Revision ID: 1ba3337a5793
Revises: 10120ac21125
Create Date: 2026-04-28 20:47:44.944356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ba3337a5793'
down_revision: Union[str, None] = '10120ac21125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('local_name', sa.String(length=100), nullable=True),
    sa.Column('scientific_name', sa.String(length=150), nullable=True),
    sa.Column('growing_season_start', sa.Integer(), nullable=True),
    sa.Column('growing_season_end', sa.Integer(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weather_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('forecast_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('planting_advisory', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_cache_district'), 'weather_cache', ['district'], unique=False)
    op.create_table('diseases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('model_class_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('treatment_organic', sa.Text(), nullable=True),
    sa.Column('treatment_chemical', sa.Text(), nullable=True),
    sa.Column('prevention_tips', sa.Text(), nullable=True),
    sa.Column('estimated_yield_loss', sa.String(length=50), nullable=True),
    sa.Column('is_contagious', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diseases_model_class_name'), 'diseases', ['model_class_name'], unique=True)
    op.create_table('farm_plots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('size_acres', sa.Float(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('irrigation_type', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_plots_farmer_id'), 'farm_plots', ['farmer_id'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('market_name', sa.String(length=150), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('price_per_bag', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_per_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_trend', sa.String(length=10), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_prices_crop_id'), 'market_prices', ['crop_id'], unique=False)
    op.create_index(op.f('ix_market_prices_recorded_at'), 'market_prices', ['recorded_at'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('predicted_disease_id', sa.UUID(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('all_predictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('treatment_advice', sa.String(length=5000), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['predicted_disease_id'], ['diseases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_created_at'), 'diagnoses', ['created_at'], unique=False)
    op.create_index(op.f('ix_diagnoses_farmer_id'), 'diagnoses', ['farmer_id'], unique=False)
    op.create_table('expert_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('is_ai_correct', sa.Boolean(), nullable=True),
    sa.Column('correct_disease_id', sa.UUID(), nullable=True),
    sa.Column('expert_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['correct_disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_reviews_diagnosis_id'), 'expert_reviews', ['diagnosis_id'], unique=False)
    op.create_table('sms_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('inbound_message', sa.Text(), nullable=True),
    sa.Column('inbound_media_url', sa.String(length=500), nullable=True),
    sa.Column('outbound_message', sa.Text(), nullable=True),
    sa.Column('diagnosis_id', sa.UUID(), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_interactions_farmer_id'), 'sms_interactions', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_sms_interactions_phone_number'), 'sms_interactions', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_interactions_phone_number'), table_name='sms_interactions')
    op.drop_index(op.f('ix_sms_interactions_farmer_id'), table_name='sms_interactions')
    op.drop_table('sms_interactions')
    op.drop_index(op.f('ix_expert_reviews_diagnosis_id'), table_name='expert_reviews')
    op.drop_table('expert_reviews')
    op.drop_index(op.f('ix_diagnoses_farmer_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_created_at'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_market_prices_recorded_at'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_crop_id'), table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_farm_plots_farmer_id'), table_name='farm_plots')
    op.drop_table('farm_plots')
    op.drop_index(op.f('ix_diseases_model_class_name'), table_name='diseases')
    op.drop_table('diseases')
    op.drop_index(op.f('ix_weather_cache_district'), table_name='weather_cache')
    op.drop_table('weather_cache')
    op.drop_table('crops')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
